Repository brainbotdev/brainbot, pull requests merged in 2020-10, with the labels that each got.

#22 October.py
  utils.py
Labels: size/XS

#26 Commands list
  .all-contributorsrc
  .bumpversion.cfg
  README.md
  main.py
Labels: command, documentation, enhancement, size/S

#28 Add contributing guidelines and code of conduct
  CONTRIBUTING.md
Labels: documentation, size/L

#30 BrainBot repeater
  .all-contributorsrc
  .bumpversion.cfg
  README.md
  main.py
  utils.py
Labels: size/M

#33 Add midhun1998 as a contributor
  .all-contributorsrc
  README.md
Labels: documentation

#34 Add translator and change cooldowns
  main.py
  requirements.txt
Labels: command, enhancement, size/S

#37 Add a git pull command
  .all-contributorsrc
  .bumpversion.cfg
  README.md
  main.py
  requirements.txt
Labels: command, enhancement, size/S

#39 #38 read cooldowns from brainbot.ini
  .gitignore
  brainbot.ini.example
  main.py
Labels: enhancement, size/S

#41 Contributing guidelines changes
  CONTRIBUTING.md
  dev-requirements.txt
Labels: documentation, size/M

#44 Add a security policy
  SECURITY.md
Labels: documentation, size/S

#45 English fix
  main.py
Labels: low priority, size/XS

#42 Make "someone tell me to" cooldown user-specific #1
  main.py
  utils.py
Labels: command, enhancement, size/S

#49 Switch to Google Translate
  main.py
  requirements.txt
Labels: command, enhancement, size/S

#51 NATO Phonetic Alphabet
  main.py
  requirements.txt
Labels: command, enhancement, size/S

#56 !phon cool down
  main.py
Labels: size/M

#69 Added !phon and !repeat dedicated cooldowns
  brainbot.ini.example
  main.py
Labels: size/S

#71 Remove bsoyka from readme for maintenance
  .all-contributorsrc
  README.md
Labels: documentation, size/XS

#72 Added !emoticon
  main.py
Labels: size/S

#74 Add more emoticons and fix Ryver markdown formatting issue.
  main.py
Labels: size/S
