Repository brainbotdev/brainbot, pull requests merged in 2020-09, with the labels that each got.

#6 main.py update
  main.py
Labels: command, enhancement

#10 Connection loss fix main.py
  main.py
Labels: enhancement

#13 Update utils.py
  utils.py
Labels: enhancement

#16 Combine cooldown class utilities
  main.py
  utils.py
Labels: enhancement, size/L
